on:
  push:
    branches:
    - main
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@3.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
