name: Bearer

on:
  push:
    branches:
      - main

jobs:
  Bearer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
        
  Anchore:
    runs-on: ubuntu-latest
    steps:
      - name: Scan current project
        uses: anchore/scan-action@v3
        with:
          path: "."

  Steampipe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: turbot/steampipe-action-setup@v1
        with:
          steampipe-version: 'latest'
          plugin-connections: |
            connection "github" {
              plugin = "github"
              token  = "${{ secrets.GITHUB_TOKEN }}"
            }
